// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	Student *head, *tmp;
	int N = 10;
	int length;

	head = makeStudent(N);
	printStudent(head);
	length = getLength(head);
	cout << "The length of the list " << length << endl;

	REQUIRE(length == 10);

	head = sortStudent(head, 1);
	printStudent(head);
	tmp = head;
	for (int i = 0; i < length - 1; i++)
	{
		REQUIRE(tmp->sum <= tmp->next->sum);
		tmp = tmp->next;
	}
	head = sortStudent(head, 0);
	printStudent(head);
	REQUIRE(head->sum == 200);
}
